/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.Random;

public class App {
    public static void main(String[] args) {

        try{
            Gson gson = new Gson();
            File recentquotesJsonFile = new File("./app/src/main/resources/recentquotes.json");
            FileReader recentquotesJsonFileReader = new FileReader(recentquotesJsonFile);
            List <Quote> quotesList = new Gson().fromJson(recentquotesJsonFileReader, new TypeToken<List<Quote>>() {}.getType());
            Random random = new Random();
            int randomNumber =random.nextInt(0, quotesList.size() - 1);
            recentquotesJsonFileReader.close();

            Quote chosenQuote = quotesList.get(randomNumber);


            System.out.println("Author: " + chosenQuote.author);
            System.out.println("Quote: " + chosenQuote.text);



        } catch (IOException e) {
            e.printStackTrace();
        }




    }


}
